host: efficiency-app-534.database.com
client_id: '3MVG9y6x0357Hlee7eCS2d6EBgF5VJPyHu63iBsIAGggrslwiDYJSb7_Zm6Wrk677e7DX8oGBmmjUlx2ws.RY'
client_secret: '7275795894435967805'
username: jeff-df12@jeffdouglas.com
password: '!dreamforce1299Qu3ph5701uGOJOJvDVywACREC'
debugging: true